name: "hiperium-trails"
services:

  trail-create-function:
    image: "hiperium/trail-create-function:1.0.0"
    container_name: "trail-create-function"
    build:
      context: functions/trail-create-function
      dockerfile: tools/docker/Dockerfile-native
    ports:
      - "9003:8080"
    env_file:
      - utils/docker/lambda.env
    volumes:
      - trails-create-volume:/var/tmp
    networks:
      - "trails-network"

  trails-localstack:
    image: localstack/localstack:latest
    container_name: "trails-localstack"
    ports:
      - "4566:4566"
    env_file:
      - utils/docker/localstack.env
    volumes:
      - trails-create-volume:/var/tmp/trails-create
      - /var/run/docker.sock:/var/run/docker.sock
      - ./functions/trail-create-function/src/test/resources/localstack/table-data.json:/var/lib/localstack/table-data.json
      - ./functions/trail-create-function/src/test/resources/localstack/table-setup.sh:/etc/localstack/init/ready.d/1_table-setup.sh
      - ./utils/docker/localstack/lambda-native-setup.sh:/etc/localstack/init/ready.d/2_lambda-setup.sh
    networks:
      - "trails-network"
    depends_on:
      - "trail-create-function"

volumes:
  trails-create-volume:

networks:
  trails-network:
